export const FETCH_STATUS = 'FETCH_STATUS';
export const FETCH_STATUS_SUCCESS = 'FETCH_STATUS_SUCCESS';
export const FETCH_STATUS_FAILED = 'FETCH_STATUS_FAILED';
export const GET_PROVIDERS = 'GET_PROVIDERS';
